version: "3.4"

services:
  php:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:rw,cached
    ports:
      - 80:80

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
###< symfony/mailer ###